events {
    worker_connections 1024;
}

http {
    # Definindo um "grupo de servidores" chamado sgcm-backend
    upstream sgcm-backend{
        # 'sgcm-app' que é o nome do container Java no Docker Compose
        server sgcm-app:8080;
    }
    server {
        listen 80; # O Nginx ouve na porta padrão da web (80)

        location / {
            # falamos que tudo que chegar nessa porta vai pro java
            proxy_pass http://sgcm-backend;

            # Configurações para passar os cabeçalhos originais
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

        }
    }
}